// <auto-generated />
using Assignment2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Assignment2.Models.Project", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProjectDescription");

                    b.Property<string>("ProjectName");

                    b.HasKey("ID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Assignment2.Models.ProjectParticipant", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Phone");

                    b.HasKey("ID");

                    b.ToTable("ProjectParticipant");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProjectParticipant");
                });

            modelBuilder.Entity("Assignment2.Models.ProjectRoster", b =>
                {
                    b.Property<string>("ProjectID");

                    b.Property<string>("ProjectParticipantID");

                    b.Property<int>("ID");

                    b.HasKey("ProjectID", "ProjectParticipantID");

                    b.HasIndex("ProjectParticipantID");

                    b.ToTable("ProjectRoster");
                });

            modelBuilder.Entity("Assignment2.Models.Client", b =>
                {
                    b.HasBaseType("Assignment2.Models.ProjectParticipant");

                    b.Property<string>("CompanyName");

                    b.ToTable("Client");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Assignment2.Models.Member", b =>
                {
                    b.HasBaseType("Assignment2.Models.ProjectParticipant");

                    b.Property<string>("Major");

                    b.ToTable("Client");

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("Assignment2.Models.ProjectRoster", b =>
                {
                    b.HasOne("Assignment2.Models.Project", "Project")
                        .WithMany("Participants")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Assignment2.Models.ProjectParticipant", "ProjectParticipant")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectParticipantID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
